using OnlineMuhasebeServer.Domain.AppEntities;
using OnlineMuhasebeServer.Domain.Repositories.GenericRepositories.AppDbContext;


namespace OnlineMuhasebeServer.Domain.Repositories.AppContext.MainRoleAndRoleRelationshipRepositories;

public interface IMainRoleAndRoleRelationshipCommandRepository : IAppCommandRepository<MainRoleAndRoleRelationship>
{

}
