namespace OnlineMuhasebeServer.Application.Features.AppFeatures.UserAndCompanyRlFeatures.Commands.RemoveByIdUserAndCompanyRl;

public sealed record RemoveByIdUserAndCompanyRlCommandResponse(string Message="Kullanıcı şirketten başarıyla çıkarıldı!");
